project:
  type: website

website:
  title: "Merete Lutz"
  navbar:
    background: lights
    search: true
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  page-footer: 
    left: "Copyright 2023, Merete Lutz"
      

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true




